/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      colors: {
        'on-primary-fixed': '#410000',
        'surface-container-lowest': '#0d0e0f',
        'surface-variant': '#343535',
        'secondary-fixed': '#e2e2e2',
        'surface-container-low': '#1a1c1c',
        'on-primary': '#690000',
        'surface-container': '#1e2020',
        'primary-container': '#800000',
        'tertiary-container': '#3d3c3c',
        'inverse-primary': '#b22b1d',
        surface: '#121414',
        'on-tertiary-fixed': '#1c1b1b',
        'on-background': '#e3e2e2',
        'on-tertiary-fixed-variant': '#474746',
        'on-primary-container': '#ff8371',
        background: '#121414',
        'on-secondary-fixed': '#1a1c1c',
        'on-secondary-container': '#b4b5b5',
        'surface-container-highest': '#343535',
        'tertiary-fixed': '#e5e2e1',
        'primary-fixed': '#ffdad4',
        'on-surface-variant': '#e2bfb9',
        'primary-fixed-dim': '#ffb4a8',
        error: '#ffb4ab',
        'surface-container-high': '#292a2a',
        'on-error-container': '#ffdad6',
        'surface-bright': '#38393a',
        'on-surface': '#e3e2e2',
        'outline-variant': '#5a413d',
        'on-secondary': '#2f3131',
        'surface-tint': '#ffb4a8',
        'on-secondary-fixed-variant': '#454747',
        'inverse-surface': '#e3e2e2',
        'inverse-on-surface': '#2f3131',
        tertiary: '#c8c6c5',
        'tertiary-fixed-dim': '#c8c6c5',
        'secondary-container': '#454747',
        'error-container': '#93000a',
        'on-primary-fixed-variant': '#8f0f07',
        'surface-dim': '#121414',
        'on-tertiary': '#313030',
        'on-tertiary-container': '#a8a6a6',
        secondary: '#c6c6c7',
        outline: '#a98984',
        primary: '#ffb4a8',
        'secondary-fixed-dim': '#c6c6c7',
        'on-error': '#690005',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        gutter: '20px',
        md: '24px',
        xl: '80px',
        base: '8px',
        lg: '48px',
        'margin-mobile': '16px',
        sm: '12px',
        'margin-desktop': '40px',
        xs: '4px',
        'section-gap': '120px',
      },
      fontFamily: {
        'headline-lg-mobile': ['Oswald'],
        'body-md': ['Montserrat'],
        'body-sm': ['Montserrat'],
        'headline-md': ['Oswald'],
        'body-lg': ['Montserrat'],
        'headline-sm': ['Oswald'],
        'label-md': ['Oswald'],
        'headline-lg': ['Oswald'],
        'display-lg': ['Oswald'],
        'label-lg': ['Oswald'],
      },
      fontSize: {
        'headline-lg-mobile': [
          '32px',
          { lineHeight: '32px', fontWeight: '700' },
        ],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '36px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-sm': ['24px', { lineHeight: '28px', fontWeight: '600' }],
        'label-md': [
          '14px',
          { lineHeight: '14px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
        'headline-lg': ['48px', { lineHeight: '48px', fontWeight: '700' }],
        'display-lg': [
          '72px',
          { lineHeight: '72px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'label-lg': [
          '16px',
          { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '500' },
        ],
      },
    },
  },
  plugins: [],
}
